name: Test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show environment
      run: |
        echo "$GITHUB_RUN_ID"
        echo "$GITHUB_RUN_NUMBER"
        echo "$GITHUB_RUN_ATTEMPT"
