name: Test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Show environment
      run: |
        echo "${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.$GITHUB_RUN_NUMBER"
        echo "${{ vars.VERSION_MAJOR }}.${{ vars.VERSION_MINOR }}.$GITHUB_RUN_NUMBER.$GITHUB_RUN_ATTEMPT"

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: List files
      run: ls -lR

  produce-artifacts:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: List files
      run: ls -lR
